Reorganize messages; Change how logging works so to make code a bit cleaner
Output redirection is now global.  The say and prompt functions allow
messages to be sent to stdout like echo and read normally would.

diff --git a/ocamlbrew b/ocamlbrew
--- a/ocamlbrew
+++ b/ocamlbrew
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Fail if we try to use an undefined value
 set -u
@@ -8,7 +8,7 @@ set -e
 #
 # Display usage message then quit
 #
-help_then_exit() {
+function help_then_exit() {
     echo Usage: "$0" [flags]
     echo
     echo "Possible flags:"
@@ -18,27 +18,52 @@ help_then_exit() {
     echo "-f         Install OCaml and findlib only, no prompts"
     echo "-s [path]  Install OCaml from Subversion [path]"
     echo "-t         Install OCaml from Subversion trunk"
-    echo "-n [name]  Install under $OCAMLBREW_BASE/[name]"
+    echo "-n [name]  Install under \$OCAMLBREW_BASE/[name]"
     echo
     echo "Subversion path should be relative to $OCAML_SVN_ROOT"
     exit 1
 }
 
 #
-# Print a message when quitting
+# Print a message when quitting due to an error
 #
-handle_error() {
-    echo Something errored out, please check the log file for details:
-    echo "$OCAMLBREW_LOGFILE"
-    echo Exiting...
+function handle_error() {
+    [ -t 3 ] && {
+        echo "Something errored out, please check the log file for details:"
+        echo "$OCAMLBREW_LOGFILE"
+        echo Exiting...
+    } >&3
+}
+
+#
+# Initialize output redirection
+#
+function init_redirect() {
+    exec 3>&1
+    exec > "$OCAMLBREW_LOGFILE"
+    exec 2>&1
+}
+
+#
+# Output which should be displayed on screen and logged
+#
+function say() {
+    echo "$*" >&3
+    echo "$*"
+}
+
+#
+# Read input without logging the input prompt
+#
+function prompt() {
+    echo -n "$*" >&3
+    read
 }
 
 #
 # Initialize lots and lots of global build and installation variables
 #
-init_variables() {
-    # Root for Subversion checkouts
-    OCAML_SVN_ROOT="http://caml.inria.fr/svn/ocaml/"
+function init_variables() {
     # Installation prefix for the software being installed
     : ${OCAMLBREW_BASE="$HOME"/ocamlbrew}
     # By default, there is no custom OCaml installation directory name
@@ -92,7 +117,7 @@ init_variables() {
 #
 # Handle command line arguments
 #
-parse_opts() {
+function parse_opts() {
     while getopts "haofs:tn:" OPTION; do
         case $OPTION in
             h)
@@ -125,19 +150,17 @@ parse_opts() {
 #
 # Display greeting, optional prompts, and summary message
 #
-greet() {
-    echo Welcome to ocamlbrew!
-    echo
-    {
+function greet() {
+    say Welcome to ocamlbrew!
+    say
     if [ "$OCAMLBREW_INSTALL_SVN" = "true" ]; then
-        echo Working with "$OCAML_SVN_ROOT""$OCAMLBREW_SVN_PATH"
+        say Working with "$OCAML_SVN_ROOT""$OCAMLBREW_SVN_PATH"
     else
-        echo Working with "$OCAML_URL"
+        say Working with "$OCAML_URL"
     fi
-    } | tee -a "$OCAMLBREW_LOGFILE"
-    echo Software will be built and installed under "$OCAML_BASE" | tee -a "$OCAMLBREW_LOGFILE"
-    echo Output will be written to "$OCAMLBREW_LOGFILE"
-    echo
+    say Software will be built and installed under "$OCAML_BASE"
+    say Output will be written to "$OCAMLBREW_LOGFILE"
+    say
 
     SHOW_CONTINUE_PROMPT="true"
     FINDLIB_INSTALL="false"
@@ -164,7 +187,7 @@ greet() {
         ODB_INSTALL="true"
     else
         # Ask the user what components they would like to install
-        read -p "Would you like to install findlib? (y/n) "
+        prompt "Would you like to install findlib? (y/n) "
         reply_lower="$(tr [A-Z] [a-z] <<< "$REPLY")"
         if [ "$reply_lower" != "y" ]; then
             FINDLIB_INSTALL="false"
@@ -176,7 +199,7 @@ greet() {
         else
             FINDLIB_INSTALL="true"
             ODB_INSTALL="true"
-            read -p "Would you like to install oasis? (y/n) "
+            prompt "Would you like to install oasis? (y/n) "
             reply_lower="$(tr [A-Z] [a-z] <<< "$REPLY")"
             if [ "$reply_lower" = "y" ]; then
                 OASIS_INSTALL="true"
@@ -184,7 +207,7 @@ greet() {
                 OASIS_INSTALL="false"
             fi
 
-            read -p "Would you like to install utop? (y/n) "
+            prompt "Would you like to install utop? (y/n) "
             reply_lower="$(tr [A-Z] [a-z] <<< "$REPLY")"
             if [ "$reply_lower" = "y" ]; then
                 UTOP_INSTALL="true"
@@ -192,7 +215,7 @@ greet() {
                 UTOP_INSTALL="false"
             fi
 
-            read -p "Would you like to install Batteries? (y/n) "
+            prompt "Would you like to install Batteries? (y/n) "
             reply_lower="$(tr [A-Z] [a-z] <<< "$REPLY")"
             if [ "$reply_lower" = "y" ]; then
                 BATTERIES_INSTALL="true"
@@ -200,7 +223,7 @@ greet() {
                 BATTERIES_INSTALL="false"
             fi
 
-            read -p "Would you like to install ocamlscript? (y/n) "
+            prompt "Would you like to install ocamlscript? (y/n) "
             reply_lower="$(tr [A-Z] [a-z] <<< "$REPLY")"
             if [ "$reply_lower" = "y" ]; then
                 OCAMLSCRIPT_INSTALL="true"
@@ -211,21 +234,21 @@ greet() {
     fi
 
     # Print a summary of what we are going to do, then continue
-    echo This script is about to:
-    echo Install OCaml
-    if "$FINDLIB_INSTALL" = "true"; then echo and install findlib; fi
-    if "$ODB_INSTALL" = "true"; then echo and install odb; fi
-    if "$OASIS_INSTALL" = "true"; then echo and install oasis; fi
-    if "$UTOP_INSTALL" = "true"; then echo and install utop; fi
-    if "$BATTERIES_INSTALL" = "true"; then echo and install Batteries; fi
-    if "$OCAMLSCRIPT_INSTALL" = "true"; then echo and install ocamlscript; fi
-    echo
+    say This script is about to:
+    say Install OCaml
+    if "$FINDLIB_INSTALL" = "true"; then say and install findlib; fi
+    if "$ODB_INSTALL" = "true"; then say and install odb; fi
+    if "$OASIS_INSTALL" = "true"; then say and install oasis; fi
+    if "$UTOP_INSTALL" = "true"; then say and install utop; fi
+    if "$BATTERIES_INSTALL" = "true"; then say and install Batteries; fi
+    if "$OCAMLSCRIPT_INSTALL" = "true"; then say and install ocamlscript; fi
+    say
 
     if [ "$SHOW_CONTINUE_PROMPT" = "true" ]; then
-        read -p "Continue (y/n)? "
+        prompt "Continue (y/n)? "
         reply_lower="$(tr [A-Z] [a-z] <<< "$REPLY")"
         if [ "$reply_lower" != "y" ]; then
-            echo Exiting...
+            say Exiting...
             rm -f "$OCAMLBREW_LOGFILE"
             exit 1
         fi
@@ -235,7 +258,7 @@ greet() {
 #
 # Create the build directory
 #
-setup_build_dir() {
+function setup_build_dir() {
     # Create and move to the build directory
     mkdir -p "$BUILD_DIR"
     pushd "$BUILD_DIR"
@@ -244,9 +267,10 @@ setup_build_dir() {
 #
 # Handle OCaml brewing
 #
-brew_ocaml() {
+function brew_ocaml() {
     case $1 in
         retrieve)
+            say Retrieving OCaml
             if [ "$OCAMLBREW_INSTALL_SVN" = "true" ]; then
                 mkdir build
                 svn checkout "$OCAML_SVN_ROOT""$OCAMLBREW_SVN_PATH" build
@@ -258,10 +282,12 @@ brew_ocaml() {
             fi
             ;;
         build)
+            say Building OCaml
             ./configure -prefix "$OCAML_BASE"
             make world.opt
             ;;
         install)
+            say Installing OCaml
             make install
             # Install the compiler libraries as well.  They are needed for utop and some
             # other projects.
@@ -279,18 +305,21 @@ brew_ocaml() {
 #
 # Handle findlib brewing
 #
-brew_findlib() {
+function brew_findlib() {
     case $1 in
         retrieve)
+            say Retrieving findlib
             curl -O "$FINDLIB_URL"
             ;;
         build)
+            say Extracting and building findlib
             tar xzf findlib-$FINDLIB_VERSION.tar.gz
             cd findlib-$FINDLIB_VERSION
             ./configure
             make all opt
             ;;
         install)
+            say Installing and configuring findlib
             make install
             # Extra configuration for OCaml libraries with C stubs, as recommended by the
             # findlib documentation.
@@ -303,9 +332,10 @@ brew_findlib() {
 #
 # Handle odb brewing
 #
-brew_odb() {
+function brew_odb() {
     case $1 in
         retrieve)
+            say Retrieving the latest version of odb.ml
             cd "$OCAML_BASE"/bin
             curl -O https://raw.github.com/thelema/odb/master/odb.ml
             chmod +x odb.ml
@@ -334,7 +364,8 @@ brew_odb() {
 #
 # Install packages with odb, potentially with some extra setup
 #
-install_with_odb() {
+function install_with_odb() {
+    say Installing "$1" with odb.ml
     case $1 in
         oasis)
             odb.ml oUnit fileutils
@@ -356,9 +387,9 @@ install_with_odb() {
 #
 # Print a friendly closing message
 #
-closing_message() {
-    echo
-    echo "You may want to add the following line to your ~/.bashrc so that OCaml is
+function closing_message() {
+    say
+    say "You may want to add the following line to your ~/.bashrc so that OCaml is
 readily available to use:
 
 source $OCAML_BASE/etc/ocamlbrew.bashrc
@@ -368,80 +399,71 @@ Enjoy!"
 
 # Print out a message to let the user know they should check the output log
 # when an error occurs
-trap "handle_error" ERR
+trap "handle_error" EXIT ERR
 
-###################################
-# This is where the magic begins! #
-###################################
+################################
+# This is where the fun begins #
+################################
+
+# Root for Subversion checkouts
+OCAML_SVN_ROOT="http://caml.inria.fr/svn/ocaml/"
 
 # Preparation
 parse_opts "$@"
 init_variables
+init_redirect
 greet
-setup_build_dir >> "$OCAMLBREW_LOGFILE" 2>&1
+setup_build_dir
 
 # OCaml
-echo Retrieving OCaml | tee -a "$OCAMLBREW_LOGFILE"
-brew_ocaml "retrieve" >> "$OCAMLBREW_LOGFILE" 2>&1
-echo Building OCaml | tee -a "$OCAMLBREW_LOGFILE"
-brew_ocaml "build" >> "$OCAMLBREW_LOGFILE" 2>&1
-echo Installing OCaml | tee -a "$OCAMLBREW_LOGFILE"
-brew_ocaml "install" >> "$OCAMLBREW_LOGFILE" 2>&1
+brew_ocaml "retrieve"
+brew_ocaml "build"
+brew_ocaml "install"
 
 # Setup the path so that OCaml is visible
 PATH="$OCAML_BASE"/bin:$PATH
 # Make sure we have an etc directory to put configuration files in
-mkdir -p "$OCAML_BASE"/etc >> "$OCAMLBREW_LOGFILE" 2>&1
+mkdir -p "$OCAML_BASE"/etc
 # Create a sourceable environment
 echo export PATH="$OCAML_BASE"/bin:\$PATH > "$OCAML_BASE"/etc/ocamlbrew.bashrc
 
 # findlib
 if [ "$FINDLIB_INSTALL" = "true" ]; then
-    echo Retrieving findlib | tee -a "$OCAMLBREW_LOGFILE"
-    brew_findlib "retrieve" >> "$OCAMLBREW_LOGFILE" 2>&1
-
-    echo Extracting and building findlib | tee -a "$OCAMLBREW_LOGFILE"
-    brew_findlib "build" >> "$OCAMLBREW_LOGFILE" 2>&1
-
-    echo Installing and configuring findlib | tee -a "$OCAMLBREW_LOGFILE"
-    brew_findlib "install" >> "$OCAMLBREW_LOGFILE" 2>&1
+    brew_findlib "retrieve"
+    brew_findlib "build"
+    brew_findlib "install"
 fi
 
 # odb
 if [ "$ODB_INSTALL" = "true" ]; then
-    echo Retrieving the latest version of odb.ml | tee -a "$OCAMLBREW_LOGFILE"
-    brew_odb "retrieve" >> "$OCAMLBREW_LOGFILE" 2>&1
-    brew_odb "configure" >> "$OCAMLBREW_LOGFILE" 2>&1
+    brew_odb "retrieve"
+    brew_odb "configure"
 fi
 
 # oasis
 if [ "$OASIS_INSTALL" = "true" ]; then
-    echo Installing oasis using odb.ml | tee -a "$OCAMLBREW_LOGFILE"
-    install_with_odb "oasis" >> "$OCAMLBREW_LOGFILE" 2>&1
+    install_with_odb "oasis"
 fi
 
 # utop
 if [ "$UTOP_INSTALL" = "true" ]; then
-    echo Installing utop using odb.ml | tee -a "$OCAMLBREW_LOGFILE"
-    install_with_odb "utop" >> "$OCAMLBREW_LOGFILE" 2>&1
+    install_with_odb "utop"
 fi
 
 # Batteries
 if [ "$BATTERIES_INSTALL" = "true" ]; then
-    echo Installing Batteries using odb.ml | tee -a "$OCAMLBREW_LOGFILE"
-    install_with_odb "batteries" >> "$OCAMLBREW_LOGFILE" 2>&1
+    install_with_odb "batteries"
 fi
 
 # ocamlscript
 if [ "$OCAMLSCRIPT_INSTALL" = "true" ]; then
-    echo Installing ocamlscript using odb.ml | tee -a "$OCAMLBREW_LOGFILE"
-    install_with_odb "ocamlscript" >> "$OCAMLBREW_LOGFILE" 2>&1
+    install_with_odb "ocamlscript"
 fi
 
 # All done!
 
-echo Done! | tee -a "$OCAMLBREW_LOGFILE"
-popd >> "$OCAMLBREW_LOGFILE" 2>&1
+say Done!
+popd
 
 closing_message
 
